### ISSUE TITLE
Set the company CI font

### ISSUE THREAD

**Issue by davidgatti** [0x4447/whatismyip.demo.0x4447.com#1]
Set the same Roboto Mono and weight font :) `Light` instead of `Thin`, I know that the home page have Thin, but I think Light will look better and I'd like to see it first here before we change it on the home page.

**Comment by davidgatti** [comment]
@radiantdinosaurs WARNING - after seeing how the other two pages that you did. Let's use `Thin`, it actually `Light` look to thick.

**Comment by radiantdinosaurs** [comment]
I just realized on the other two issues, the font didn't look right because I linked the folder up wrong. I put 'fonts' instead of 'font' in the path. If you make another issue of those, I can correct it. Also, this is what the actual 300 weight looks like vs. the 100 weight:
<img width="704" alt="screen shot 2018-10-22 at 11 07 33 am" src="https://user-images.githubusercontent.com/8292853/47310015-c50fa300-d5ea-11e8-8489-78c2dba7a111.png">
<img width="604" alt="screen shot 2018-10-22 at 11 07 54 am" src="https://user-images.githubusercontent.com/8292853/47310017-c50fa300-d5ea-11e8-9f04-16f5f093ed20.png">
Which one do you prefer?

**Comment by davidgatti** [comment]
OO, ok – then lets keep it to `Light` for now. And also you can make your own Issue, and assign yourself, and then do what you need to do, and make a PR for me to check if there is something wrong that you know about :) 

A simple rule of thumb is that: if you know it is wrong, I'll 99% of the time think the same. The only expect could be that if fixing would take so long that it won't be worth it. Normally small things less then few hours are always worth fixing :)
